replaceitem entity @s slot.inventory 0 barrier
replaceitem entity @s slot.inventory 1 barrier
replaceitem entity @s slot.inventory 2 barrier
replaceitem entity @s slot.inventory 3 barrier
replaceitem entity @s slot.inventory 4 barrier
replaceitem entity @s slot.inventory 5 barrier
replaceitem entity @s slot.inventory 6 barrier
replaceitem entity @s slot.inventory 7 barrier
replaceitem entity @s slot.inventory 8 barrier
replaceitem entity @s slot.inventory 9 barrier
replaceitem entity @s slot.inventory 10 barrier
replaceitem entity @s slot.inventory 11 barrier
replaceitem entity @s slot.inventory 12 barrier
replaceitem entity @s slot.inventory 13 barrier
replaceitem entity @s slot.inventory 14 barrier
replaceitem entity @s slot.inventory 15 barrier
replaceitem entity @s slot.inventory 16 barrier
replaceitem entity @s slot.inventory 17 barrier
replaceitem entity @s slot.inventory 18 barrier
replaceitem entity @s slot.inventory 19 barrier
replaceitem entity @s slot.inventory 20 barrier
replaceitem entity @s slot.inventory 21 barrier
replaceitem entity @s slot.inventory 22 barrier
replaceitem entity @s slot.inventory 23 barrier
replaceitem entity @s slot.inventory 24 barrier
replaceitem entity @s slot.inventory 25 barrier
replaceitem entity @s slot.inventory 26 barrier
replaceitem entity @s slot.hotbar 0 barrier
replaceitem entity @s slot.hotbar 1 barrier
replaceitem entity @s slot.hotbar 2 barrier
replaceitem entity @s slot.hotbar 3 barrier
replaceitem entity @s slot.hotbar 4 barrier
replaceitem entity @s slot.hotbar 5 barrier
replaceitem entity @s slot.hotbar 6 barrier
replaceitem entity @s slot.hotbar 7 barrier
replaceitem entity @s slot.hotbar 8 barrier